//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NewSceneEditor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NEWSCENEEDITOR_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define IDD_NPC_PAGE                    130
#define IDD_OBJ_PAGE                    131
#define IDD_TRAP_PAGE                   132
#define IDR_ACCELERATOR1                132
#define IDD_OBJ_TRAP_RDLG               135
#define IDD_NPC_RDLG                    136
#define IDD_PATH_KEY_POS_RDLG           138
#define IDD_MODE_CHOICE                 139
#define IDD_AI_CHECK_DLG                140
#define IDD_DIALOG1                     141
#define IDD_DYNAMIC_FILE_SEL            143
#define IDD_AREA_EDIT                   145
#define IDD_SET_CENTER_POS              146
#define IDD_SET_OFFSET_POSITION         147
#define IDD_ELEMENT_TAB                 148
#define IDD_COLONY_EDIT                 149
#define IDC_CHECK1                      1000
#define IDC_SHOW_PATH                   1000
#define IDC_NO_CHECK                    1000
#define IDC_AUTO_OPEN_FILE              1000
#define IDC_BUTTON1                     1001
#define IDC_NPC_NAME                    1001
#define IDC_LIST1                       1002
#define IDC_CHECK2                      1002
#define IDC_GRID_LINE                   1002
#define IDC_NORMAL                      1002
#define IDC_SKIP                        1002
#define IDC_AUTO_OPEN_AREA_FILE         1002
#define IDC_CHECK3                      1003
#define IDC_SHOW_NPC                    1003
#define IDC_BOSS_LIST                   1003
#define IDC_DELETE                      1003
#define IDC_CHECK4                      1004
#define IDC_SHOW_OBJ                    1004
#define IDC_SERVANT_LIST                1004
#define IDC_MAP_VIEW                    1005
#define IDC_CHECK5                      1006
#define IDC_SHOW_TRAP                   1006
#define IDC_TESTBTN                     1007
#define IDC_SHOW_AREA                   1007
#define IDC_BUTTON2                     1008
#define IDC_SHOW_BLOCK                  1008
#define IDC_VIEW_SCALING                1009
#define IDC_BUTTON3                     1009
#define IDC_RESET                       1010
#define IDC_SHOW_ARROW                  1011
#define IDC_BUTTON4                     1012
#define IDC_SET_COLOR                   1012
#define IDC_ZOOM1                       1013
#define IDC_BUTTON6                     1013
#define IDC_ZOOM2                       1014
#define IDC_SHOW_GAME_VIEW              1015
#define IDC_SHOW_FOLLOW_MOUSE           1016
#define IDC_GRID_X                      1017
#define IDC_Direction                   1018
#define IDC_GRID_Y                      1018
#define IDC_ELEMENT_TAB                 1019
#define IDC_maxDelayTime                1019
#define IDC_EDIT1                       1020
#define IDC_SHOW_NPC_FULL               1020
#define IDC_ELEMENT_COUNT               1021
#define IDC_GRID_X2                     1021
#define IDC_EDIT2                       1021
#define IDC_PLAYER_NUM                  1021
#define IDC_NAME                        1022
#define IDC_PLAYER_NUM2                 1022
#define IDC_MAX_PLAYER_NUM              1022
#define IDC_GRID_Y2                     1023
#define IDC_CFG_AI                      1023
#define IDC_TAB_SHOW_ALL                1024
#define IDC_PLACE_AI                    1024
#define IDC_IGNORE_BLOCK                1024
#define IDC_TAB_SHOW_SCENE              1025
#define IDC_SHOW_SELECT                 1026
#define IDC_PEN_SIZE                    1027
#define IDC_TRANSPARENCE                1028
#define IDC_DRAW_AREA                   1029
#define IDC_FILL_AREA                   1030
#define IDC_ERASE_AREA                  1031
#define IDC_COMBO1                      1032
#define IDC_PEN_SIZE_SHOW               1032
#define IDC_AREA_COLOR_SHOW             1033
#define IDC_IS_FB                       1033
#define IDC_AREA_NAME                   1034
#define IDC_TRANSPARENCE_SHOW           1035
#define IDC_DONOT_OVER                  1036
#define IDC_MUSIC                       1037
#define IDC_BARRIER_OBJ                 1038
#define IDC_AREA_FB                     1040
#define IDC_SEARCH_NAME                 1041
#define IDC_DYNAMIC                     1041
#define IDC_PATH_EDIT                   1042
#define IDC_EDIT3                       1044
#define IDC_DEFAULT_AI                  1044
#define IDC_EDIT4                       1045
#define IDC_MOVE_RANGE                  1046
#define IDC_LIST3                       1046
#define IDC_minDelayTime                1047
#define IDC_NEWNAME                     1048
#define IDC_MAP_LIST                    1049
#define IDC_BUTTON5                     1050
#define IDC_BUTTON7                     1052
#define IDC_ROTATE                      1052
#define IDC_FIND_IN_BARRIER             1053
#define IDC_AREA_STATE                  1054
#define IDC_AREA_MUSIC_EDIT             1055
#define IDC_DELETE_AREA                 1056
#define IDC_MODIFY                      1057
#define IDC_MOVE_MAP                    1059
#define IDC_FIND                        1060
#define IDC_ELEMENT_LIST                1061
#define IDC_FINDSTRING                  1062
#define IDC_SET_GRID_MID                1063
#define IDC_SET_GRID_MIDDLE             1063
#define IDC_NEW_ELEMENT                 1063
#define IDC_X                           1064
#define IDC_DEL_ELEMENT                 1064
#define IDC_Y                           1065
#define IDC_EDIT_ELEMENT                1065
#define IDC_NORMAL_LIST                 1065
#define IDC_SET_CENTER_POS              1066
#define IDC_LIST_MEMBER                 1066
#define IDC_SET_BOSS                    1067
#define IDC_ADD_NPC                     1068
#define IDC_COPY_AND_PUT                1069
#define IDC_RULER                       1070
#define IDC_COMBO3                      1073
#define IDC_COMBO4                      1074
#define IDC_IGNORE_CLOG                 1075
#define IDC_IGNORE_CLOG1                1076
#define IDC_IDLEACT                     1078
#define IDC_Search                      1079
#define IDC_AISET                       1080
#define IDC_INSERT                      1081
#define IDC_DEFAULTAI                   1099
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_LOAD_MAP                     32776
#define ID_LOAD_SCENE                   32777
#define ID_LOAD_AREA                    32778
#define ID_SAVE_SCENE                   32779
#define ID_SAVE_AREA                    32780
#define ID_32781                        32781
#define ID_32782                        32782
#define ID_SET_OFFSET_POSITION          32785
#define ID_32786                        32786
#define ID_R                            32787
#define ID_RESAVE_ALL_SCENE_FILE        32788
#define ID_32789                        32789
#define ID_RESAVE_ALL_AREA_FILE         32790
#define ID_32791                        32791
#define ID_RESAVE_ALL_DYNAMIC_FILE      32792
#define ID_32793                        32793
#define ID_SAVE_TRAP                    32794
#define ID_SAVE_TRANS_AREA              32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
