CAssociationFriendListWnd		= class(SQRDialog)
CAssociationFriendListItem		= class(SQRDialog)
CAssociationFriendListItemChild	= class(SQRDialog)
CAssociationClassTitleIcon		= class(SQRDialog)
CAssociationAddClassEdit		= class(SQRDialog)
