--
--local function GetDropRate(PkValue, Level)
--	local Rate = 0
--	if PkValue == 1 then 
--		Rate = 0.6
--	else
--		Rate = 3
--	end
--	return math.floor(Rate * (EquipUpgrade_Common[Level].VanishSoulCount))
--	
--	local DropRate = 0
--	if PkValue < 4 then
--		DropRate = 1
--	elseif PkValue < 8 then
--		DropRate = 2
--	elseif PkValue < 14 then
--		DropRate = 3
--	elseif PkValue < 20 then
--		DropRate = 4
--	else
--		DropRate = 5
--	end
--	return DropRate*PkValue
--end
--
--local function PlayerDeadDropObjs(PlayerId, DeadScene, DeadPos, DropObjTbl)
--	NpcDropObjTbl[EntityID] = DropObjTbl
--	NpcDropObjTbl[EntityID].m_CreateObjTbl = {}
--	
--	local x,y = DeadPos.x,DeadPos.y
--	local Obj
--	local dispos 
--	local objtbl
--	local ObjName
--	local FPos = CFPos:new()
--	local DropOwnerId
--	local DropTime
--	local BelongToTeam
--	local QuestDropOwnner
--	local CreateNum = table.getn(DropObjTbl.m_Objs_List)
--	for i=1,CreateNum do
--		dispos = DropPosTbl[1]
--		objtbl = DropObjTbl.m_Objs_List[i]
--		ObjName = objtbl[1]
--		table.remove(DropPosTbl,1)
--		table.insert(DropPosTbl,dispos)
--		FPos.x = x + dispos[1]
--		FPos.y = y + dispos[2]
--		DropOwnerId = PlayerId
--		DropTime = os.time()
--		BelongToTeam = DropObjTbl.m_BelongToTeam
--		local IntObjCommon = IntObj_Common(ObjName)
--		if IntObjCommon then
--			QuestDropOwnner = objtbl["QuestDropOwner"]
--			if QuestDropOwnner then
--				--如果是任务物品,那么只有本人可以拾取
--				DropTime = nil  --不指定掉落时间
--				DropOwnerId = nil
--			end
--			
--			if BelongToTeam and BelongToTeam ~= 0 and IntObjCommon("TriggerAction") ~= "可拾取的Obj" then
--				DropOwnerId = nil
--			end
--			Obj = CreateIntObj( DeadScene, FPos, ObjName,true, DropOwnerId, BelongToTeam,DropTime)
--			Obj.m_QuestDropObjOwnner = QuestDropOwnner
--		end
--	end
--end
--
--玩家死亡掉落囧
--先掉魂, 然后掉物品, 掉钱
--@param Killed 被杀玩家
--@param Killer 杀人玩家
--/**旧PK代码**/
--function PlayerDeadDrop(Killed, Killer)
--	local PkValue = Killed.m_Properties:GetPkValue()
--	if PkValue == 0 then
--		return
--	end
--	
--	local DeadSceneId = Killed.m_Scene.m_SceneId
--	local DeadPos = CPos:new()
--	Killed:GetGridPos(DeadPos)
--	local KilledName = Killed.m_Properties:GetCharName()
--	local KillerName = Killer.m_Properties:GetCharName()
--	
--	local data = {}
--	data["PlayerId"]		= Killed.m_uID
--	data["AddPlayerId"] = Killer.m_uID
--	data["soulCount"] 	= GetDropRate(PkValue, Killed:CppGetLevel())
--	
--	local function CallBack(result, result2)
--	
--		if IsCppBound(Killed) then
--			if result["SoulRet"] ~= nil then
--				MsgToConn(Killed.m_Conn, 193003, KillerName, result["soulCount"])
--				Gas2Gac:ReturnModifyPlayerSoulNum(Killed.m_Conn,result["SoulRet"])
--			end
--		end
--		
--		if IsCppBound(Killer) then
--			if result2["SoulRet"] ~= nil then
--				MsgToConn(Killer.m_Conn, 193009, KilledName, result2["soulCount"])
--				Gas2Gac:ReturnModifyPlayerSoulNum(Killer.m_Conn,result2["SoulRet"])
--			end
--		end
--		
----		local DeadScene = g_SceneMgr:GetScene(DeadSceneId)
----		if DeadScene and #(result["DropObjList"]) > 0 then
----			SaveAllDropObjs(PlayerId, EntityID,DeadScene,DeadPos,DropObjTbl)
----		end
--	end
--	CallAccountAutoTrans(Killed.m_Conn.m_Account, "CharacterMediatorDB", "KillPlayerDropObj", CallBack, data, Killer.m_AccountID)
--end
