CSceneBase = class()

gas_require "world/scene_mgr/SceneType/Scene"
gas_require "world/scene_mgr/SceneType/SingleScene"
gas_require "world/scene_mgr/SceneType/AreaScene"
gas_require "world/scene_mgr/SceneType/TongScene"
gas_require "world/scene_mgr/SceneType/WarZoneScene"
gas_require "world/scene_mgr/SceneType/OreAreaScene"
gas_require "world/scene_mgr/SceneType/GameScene"
gas_require "world/scene_mgr/SceneType/PVPScene"
gas_require "world/scene_mgr/SceneType/YbEducateActionScene"
gas_require "world/scene_mgr/SceneType/TongChallengeScene"
gas_require "world/scene_mgr/SceneType/KillYingFengScene"

gas_require "world/scene_mgr/SceneType/DaTaoShaScene"
gas_require "world/scene_mgr/SceneType/MercenaryMonsterScene"
gas_require "world/scene_mgr/SceneType/ScenarioExplorationScene"
gas_require "world/scene_mgr/SceneType/ScopesExplorationScene"
gas_require "world/scene_mgr/SceneType/SpecialScopesExplorationScene"
gas_require "world/scene_mgr/SceneType/PublicAreaScene"
gas_require "world/scene_mgr/SceneType/RobResScene"
gas_require "world/scene_mgr/SceneType/DareQuestScene"
gas_require "world/scene_mgr/SceneType/DaDuoBaoScene"
gas_require "world/scene_mgr/SceneType/BossBattleScene"
gas_require "world/scene_mgr/SceneType/DragonCaveScene"
