all:
	

install:
	mkdir -p /home/web_fold/lib/cis/
	cp lib/Lib.php /home/web_fold/lib/cis/
	mkdir -p /home/web_fold/conf/cis
	cp conf/Config.php.temp /home/web_fold/conf/cis/Config.php
	mkdir -p /home/web_fold/cgi-bin/cis/
	cp php/*.php /home/web_fold/cgi-bin/cis/	
	chmod +x /home/web_fold/cgi-bin/cis/*.php
