//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GUIEditor.rc
//
#define IDI_SCROLL                      5
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_FORMVIEW                    101
#define IDD_WND_GROUP                   101
#define IDD_GUIEDITOR_DIALOG            102
#define IDD_GUIEDITOR_DIALOG_800        102
#define IDD_WND_PROP                    103
#define IDD_GUIEDITOR_DIALOG_1024       104
#define IDR_MAINFRAME                   128
#define IDI_BUTTON                      131
#define IDI_CHECKBUTTON                 132
#define IDI_COMBOBOX                    133
#define IDI_ICON4                       134
#define IDI_EDIT                        134
#define IDI_ICON6                       136
#define IDI_ICON7                       137
#define IDI_LISTCTRL                    137
#define IDI_ICON8                       138
#define IDI_PROGRESS                    138
#define IDI_ICON9                       139
#define IDI_SPIN                        140
#define IDI_STATIC                      141
#define IDI_TREE                        142
#define IDI_ARROW                       143
#define IDC_EDITOR_ARROW                147
#define IDC_EDITOR_BUTTON               148
#define IDC_EDITOR_CHECKBUTTON          149
#define IDC_EDITOR_COMBOBOX             150
#define IDC_EDITOR_EDIT                 151
#define IDC_EDITOR_RICHWND              152
#define IDC_EDITOR_LISTCTRL             153
#define IDD_CHOOSE_SOUND                153
#define IDD_SELECT_SOUND                153
#define IDC_EDITOR_PROGRESS             154
#define IDC_EDITOR_SCROLLBAR            155
#define IDC_EDITOR_SPIN                 156
#define IDC_EDITOR_STATIC               157
#define IDC_EDITOR_TREECTRL             158
#define IDI_EDITORWND                   159
#define IDC_EDITOR_WNDMOVE              159
#define IDI_WNDG_NOR                    160
#define IDI_WNDG_SEL                    161
#define IDC_EDITOR_WNDMOVE1             161
#define IDC_EDITOR_CLOCK                161
#define IDI_EDITORWNDUNIT               162
#define IDC_EDITOR_RICHWND1             162
#define IDC_EDITOR_CHART                162
#define IDB_LOGO                        163
#define IDI_TEXTURE                     165
#define IDI_TEXTUREEDIT                 166
#define IDD_DIALOG_SELECT_SIZE          166
#define IDI_ICON1                       167
#define IDI_RICHWND                     167
#define IDD_STYLE                       168
#define IDI_CLOCK                       169
#define IDD_WND_DEFAULT                 169
#define IDI_WNDEMBED1                   170
#define IDI_WNDMOVE                     170
#define IDI_CHART                       171
#define IDI_CWND                        172
#define IDD_WND_FACE                    173
#define IDD_DIALOGBAR                   175
#define IDD_FLASH_EDIT                  176
#define IDD_WND_TEXFONT                 177
#define IDD_DLG_GUIRES                  179
#define IDI_ICON                        180
#define IDI_ICON2                       181
#define IDI_VIDEO                       181
#define IDC_ABUTTON                     1001
#define IDC_EDITORWNDLIST               1002
#define IDC_ABUTTON1                    1003
#define IDC_IMPORT                      1003
#define IDC_FLIPH                       1003
#define IDC_REDO                        1003
#define IDC_AEDIT1                      1004
#define IDC_FLIPV                       1004
#define IDC_LOAD                        1004
#define IDC_COMBO1                      1006
#define IDC_WND_FONT                    1006
#define IDC_WND_BKTYPE                  1006
#define IDC_STYLE_SELECT                1006
#define IDC_LANGUAGE_LIST               1006
#define IDC_FACE_SELECT_CUR             1006
#define IDC_COMBO2                      1007
#define IDC_BK_STYLE                    1007
#define IDC_WND_BKTYPE2                 1007
#define IDC_AUDIO_TYPE                  1007
#define IDC_FACE_SELECT_ALL             1007
#define IDC_AEDIT9                      1008
#define IDC_BK_TEXTURE                  1008
#define IDC_WND_NineBlock               1008
#define IDC_ASTATIC                     1009
#define IDC_SHOW                        1010
#define IDC_CHART                       1010
#define IDC_CWnd                        1011
#define IDC_AICON                       1011
#define IDC_WND_FONT_TYPE               1012
#define IDC_VIDEO                       1012
#define IDC_BK_DOWN                     1013
#define IDC_CANCEL                      1013
#define IDC_AICON2                      1013
#define IDC_VIDEO2                      1013
#define IDC_FLASHCONTROL                1013
#define IDC_BK_COLOR                    1014
#define IDC_AEDIT_POS                   1015
#define IDC_AEDIT_BK                    1016
#define IDC_PRE_VIEW                    1017
#define IDC_WND_TREE                    1019
#define IDC_TEXT_BROWN                  1020
#define IDC_TEXT_BROWN2                 1021
#define IDC_TEXT_CLEAR                  1021
#define IDC_CHECK1                      1022
#define IDC_SIZEFOLLOW                  1022
#define IDC_BK_COPY                     1023
#define IDC_CHECK2                      1023
#define IDC_ACHECKBUTTON                1024
#define IDC_CHECK3                      1024
#define IDC_ACOMBOBOX                   1025
#define IDC_CHECK4                      1025
#define IDC_AEDIT                       1026
#define IDC_CHECK5                      1026
#define IDC_ARICHTEXT                   1027
#define IDC_CHECK6                      1027
#define IDC_APROGRESS                   1028
#define IDC_CHECK7                      1028
#define IDC_ASCROLLBAR                  1029
#define IDC_CHECK8                      1029
#define IDC_ASPIN                       1030
#define IDC_CHECK9                      1030
#define IDC_ABUTTON2                    1031
#define IDC_SAVE_AS                     1031
#define IDC_UNDO                        1031
#define IDC_CHECK10                     1031
#define IDC_AEDIT2                      1032
#define IDC_WND_NAME                    1032
#define IDC_TAB1                        1032
#define IDC_EDIR_TAB                    1032
#define IDC_AWNDMOVE                    1032
#define IDC_CHECK11                     1032
#define IDC_AEDIT_TEXTCOLOR1            1032
#define IDC_SAVE2                       1033
#define IDC_SAVE                        1033
#define IDC_LIST_PROP                   1033
#define IDC_AEDIT_FONT_TEXTCOLOR        1033
#define IDC_CHECK12                     1033
#define IDC_AEDIT3                      1034
#define IDC_WND_STYLE                   1034
#define IDC_AEDIT_TEXTBCCOLOR           1034
#define IDC_CHECK13                     1034
#define IDC_A2                          1034
#define IDC_IECONTROL                   1034
#define IDC_WND_X                       1035
#define IDC_CLOCK                       1035
#define IDC_AEDIT_TEXTCOLOR2            1035
#define IDC_CHECK14                     1035
#define IDC_AEDIT_FONT_TEXTCOLOR1       1036
#define IDC_AEDIT6                      1037
#define IDC_WND_WIDTH                   1037
#define IDC_LIST_IMAGE                  1037
#define IDC_AEDIT7                      1038
#define IDC_WND_HEIGHT                  1038
#define IDC_LIST_IMAGEPROP              1038
#define IDC_RADIO_POS                   1038
#define IDC_RADIO10                     1039
#define IDC_ALISTCTRL                   1039
#define IDC_LIST_IMAGEPROP2             1039
#define IDC_RADIO11                     1040
#define IDC_ATREECTRL                   1040
#define IDC_RADIO12                     1041
#define IDC_AARROW                      1041
#define IDC_WND_GROUPID                 1042
#define IDC_RADIO_TEX                   1042
#define IDC_AEDIT8                      1043
#define IDC_WND_FONTSIZE                1043
#define IDC_RADIO_PREVIEW               1043
#define IDC_AEDIT10                     1044
#define IDC_BK_LEFT                     1044
#define IDC_AEDIT11                     1045
#define IDC_BK_TOP                      1045
#define IDC_ABUTTON3                    1045
#define IDC_SET_WORKPATH                1045
#define IDC_AEDIT12                     1046
#define IDC_BK_RIGHT                    1046
#define IDC_ABUTTON4                    1046
#define IDC_BTN_BKTEX                   1046
#define IDC_AEDIT13                     1047
#define IDC_BK_BOTTOM                   1047
#define IDC_RADIO_800                   1047
#define IDC_RADIO2                      1048
#define IDC_RADIO_1024                  1048
#define IDC_TREE1                       1051
#define IDC_TREE_RES                    1051
#define IDC_BUTTON1                     1052
#define IDC_IS_SHOW_BACK                1053
#define IDC_BTN_ALIGN_RIGHT             1053
#define IDC_BTN_BKCLR                   1054
#define IDC_BTN_CLR                     1055
#define IDC_BTN_CLR1                    1055
#define IDC_CHECK_SHADOW                1056
#define IDC_BTN_ALIGN_TOP               1056
#define IDC_CHECK_ITALIC                1057
#define IDC_BLOCK_LEFT                  1058
#define IDC_BTN_ALIGN_BOTTOM            1058
#define IDC_CHECK_OUTLINE               1059
#define IDC_BLOCK_LEFT_BOTTOM           1059
#define IDC_BTN_CLR2                    1060
#define IDC_BLOCK_BOTTOM                1060
#define IDC_BTN_ALIGN_WIDTH             1060
#define IDC_CHECK_OUTLINE2              1061
#define IDC_CHECK_GRADUAL               1061
#define IDC_BLOCK_CENTER                1061
#define IDC_BUTTON6                     1061
#define IDC_BTN_ALIGN_HEIGHT            1061
#define IDC_ALPHA_EDIT                  1062
#define IDC_BLOCK_TOP                   1062
#define IDC_CHOOSE_TEXTURE              1063
#define IDC_BLOCK_RIGHT_TOP             1063
#define IDC_SHOWALPHA                   1064
#define IDC_BLOCK_RIGHT                 1064
#define IDC_CHOOSE_AUDIO                1064
#define IDC_Style_OK                    1065
#define IDC_CHOOSE_AUDIO2               1065
#define IDC_CLEAR_AUDIO                 1065
#define IDC_Style_Add                   1066
#define IDC_Style_Del                   1067
#define IDC_Style_Save                  1068
#define IDC_EDIT1                       1069
#define IDC_Select_Pic                  1070
#define IDC_BLOCK_RIGHT_BOTTOM          1071
#define IDC_STYLE_SOK                   1072
#define IDC_CHECK_FONT_OUTLINE          1073
#define IDC_EDIT_TOP                    1074
#define IDC_EDIT_LEFT                   1075
#define IDC_EDIT_RIGHT                  1076
#define IDC_EDIT_BOTTOM                 1077
#define IDC_Replace_All                 1078
#define IDC_CHECK_ALPHATEST             1079
#define IDC_CHECK_AlphaBlend            1080
#define IDC_TOP_HIGHT                   1081
#define IDC_BOTTOM_HIGHT                1082
#define IDC_LEFT_WIDTH                  1083
#define IDC_EDIT5                       1084
#define IDC_RIGHT_WIDTH                 1084
#define IDC_FLASH_TIME                  1084
#define IDC_AutoTool                    1085
#define IDC_FLASH_COUNT                 1085
#define IDC_BLOCK_LEFT_TOP              1086
#define IDC_BLOCK_INDEX                 1087
#define IDC_ADD_BLOCK                   1088
#define IDC_SET_BK_COLOR                1089
#define IDC_BTN_FONT_CLR1               1089
#define IDC_AUDIONAME_EDIT              1090
#define IDC_CHECK_FONT_GRADUAL          1090
#define IDC_CHECK_EDIT_FONT             1091
#define IDC_SHOW_FONT_CONFIG_DLG        1097
#define IDC_TREE_CUES                   1100
#define IDC_EDIT3                       1100
#define IDC_FLASH_POSX                  1100
#define IDC_OK                          1101
#define IDC_FONT_NAME2                  1101
#define IDC_STATIC_TEXT                 1101
#define IDC_FLASH_POSY                  1101
#define IDC_STATIC_WIN                  1102
#define IDC_FLASH_REPOS_BY              1102
#define IDC_SLIDER_ZOOM                 1103
#define IDC_FLASH_POSH                  1103
#define IDC_SLIDER_WIN                  1104
#define IDC_FLASH_REPOS_TY              1104
#define IDC_SHOW_ZOOM                   1105
#define IDC_FLASH_POSW                  1105
#define IDC_SHOW_PIX                    1106
#define IDC_FLASH_REPOS_LX              1106
#define IDC_FLASH_REPOS_RX              1107
#define IDC_FACE_INFO                   1108
#define IDC_FLASH_AMAX                  1108
#define IDC_FACE_X                      1109
#define IDC_FLASH_AMIN                  1109
#define IDC_FACE_Y                      1110
#define IDC_FACE_W                      1111
#define IDC_FACE_H                      1112
#define IDC_FACE_OK                     1113
#define IDC_FACE_DEL                    1114
#define IDC_FACE_ID_FROM                1115
#define IDC_FACE_ID_TO                  1116
#define IDC_FACE_W_ALL                  1117
#define IDC_FACE_H_ALL                  1118
#define IDC_FACE_ADD_ALL                1119
#define IDC_FACE_DEL_ALL                1120
#define IDC_FACE_TEXTURE                1121
#define IDC_FACE_CHOOSE_TEX             1122
#define IDC_FACE_SAVE                   1123
#define IDC_FACE_COUNT                  1124
#define IDC_FACE_INFOMATION             1125
#define IDC_FACE_NEW                    1126
#define IDC_FACE_ADD_NEW                1127
#define IDC_FLASH_INFO                  1128
#define IDC_FLASH_STATA_CHOOSE          1129
#define IDC_STATE_NAME                  1130
#define IDC_FLASH_NAME_CHOOSE           1131
#define IDC_STATIC_FLASH                1132
#define IDC_FONT_KEY_CHOOSE             1132
#define IDC_FLASH_NAME_EDIT             1133
#define IDC_FLASH_ADD                   1134
#define IDC_FLASH_EDIT_OK               1135
#define IDC_FLASH_SAVE_ALL              1136
#define IDC_FLASH_TEX                   1137
#define IDC_FLASH_CHOOSE_TEX            1138
#define IDC_FLASH_DEL                   1139
#define IDC_CHECK_ADD                   1140
#define IDC_STATIC_TEXTFONT             1141
#define IDC_STATIC_TEXFONT              1142
#define IDC_FONT_TEX                    1143
#define IDC_FONT_CHOOSE_TEX             1144
#define IDC_FONT_ADD                    1145
#define IDC_FONT_KEY_CHOOSE_CUR         1146
#define IDC_FONT_WORD_CHOOSE            1147
#define IDC_FONT_POSX                   1148
#define IDC_FONT_POSY                   1149
#define IDC_FONT_POSW                   1150
#define IDC_FONT_POSH                   1151
#define IDC_FONT_DEL                    1152
#define IDC_FONT_EDIT_OK                1153
#define IDC_FONT_SAVE_ALL               1154
#define IDC_EDIT_FONT_SIZE              1156
#define IDC_AEDIT_FONT_TEXTBCCOLOR      1157
#define IDC_BTN_FONT_CLR                1158
#define IDC_BTN_FONT_BKTEX              1159
#define IDC_CHECK_FONT_ITALIC           1160
#define IDC_CHECK_FONT_SHADOW           1161
#define IDC_BUTTON_FONT_OK              1162
#define IDC_CHECK_RES                   1163
#define IDC_BTN_REFRESH                 1166
#define IDC_EDITOR_AICON                1167
#define IDC_BTN_ALIGN_LEFT              1167
#define IDC_EDITOR_VIDEO                1168
#define IDC_EDITOR_FLASHCONTROL         1169
#define IDC_EDITOR_IECONTROL			1170

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1168
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
