//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MapEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MapEditorTYPE               129
#define IDD_PANDLG                      130
#define IDD_SET                         136
#define IDR_SETICO                      146
#define IDR_SET                         146
#define IDR_3DICOSEL                    147
#define IDR_2DICONOR                    148
#define IDR_2DICOSEL                    149
#define IDR_SETGROUPNOR                 151
#define IDR_GROUP                       151
#define IDR_SETGROUPSEL                 152
#define IDR_GROUPSEL                    152
#define IDR_SETUNIT                     153
#define IDD_SCENARIO                    153
#define IDR_SETUNIT3D                   154
#define IDR_UNEDITED3D                  154
#define IDR_ACCELERATOR1                155
#define IDR_F1                          156
#define IDD_NEWMAP                      158
#define IDI_EDITED                      165
#define IDI_EDITED2D                    165
#define IDI_3DSETSEL                    167
#define IDI_2DSETSEL                    168
#define IDI_3DSET                       169
#define IDI_2DSET                       170
#define IDI_UNEDITED2D                  171
#define IDI_EDITED3D                    172
#define IDI_FXUNIT                      173
#define IDI_FXUNITSEL                   174
#define IDC_CHECK1                      1000
#define IDC_SHADOW                      1000
#define IDC_BUTTON1                     1001
#define IDC_GrassSet                    1001
#define IDC_CREATESET                   1001
#define IDC_RADIO1                      1002
#define IDC_MudSet                      1002
#define IDC_DELETESET                   1002
#define IDC_PHYSICHEIGHT                1002
#define IDC_LOWBLOCK                    1002
#define IDC_LIST1                       1003
#define IDC_LOGIC                       1003
#define IDC_LOGICHEIGHT                 1003
#define IDC_RADIO2                      1003
#define IDC_BLOCKMASK                   1003
#define IDC_RADIO3                      1004
#define IDC_RADIO4                      1005
#define IDC_LAYERONE                    1006
#define IDC_RADIO5                      1006
#define IDC_LAYERTWO                    1007
#define IDC_RADIO6                      1007
#define IDC_LINEAR2                     1008
#define IDC_LINEAR                      1008
#define IDC_BLOCKTYPE                   1008
#define IDC_GAUSS2                      1009
#define IDC_GAUSS                       1009
#define IDC_HEIGHT                      1009
#define IDC_LINEAR3                     1010
#define IDC_X                           1010
#define IDC_LINEAR4                     1011
#define IDC_Z                           1011
#define IDC_LINEAR5                     1012
#define IDC_BOTH                        1012
#define IDC_MIDBLOCK                    1014
#define IDC_LINEAR6                     1015
#define IDC_UP                          1015
#define IDC_HIGHBLOCK                   1015
#define IDC_LINEAR8                     1016
#define IDC_DOWN                        1016
#define IDC_TREE1                       1017
#define IDC_LINEAR9                     1017
#define IDC_CLEAR                       1017
#define IDC_EDITX                       1019
#define IDC_STATICROLL                  1020
#define IDC_STATICPOS                   1021
#define IDC_STATICFOV                   1022
#define IDC_EDITY                       1023
#define IDC_EDITZ                       1024
#define IDC_EDITFOV                     1025
#define IDC_SETLIST                     1025
#define IDC_EDITROLL                    1026
#define IDC_SETVIEW                     1026
#define IDC_GROUPNAME                   1027
#define IDC_CREATEGROUP                 1028
#define IDC_CREATEUNIT                  1029
#define IDC_DELETEGROUP2                1030
#define IDC_DELETEGROUP                 1030
#define IDC_SLIDER1                     1030
#define IDC_STRENGTH                    1030
#define IDC_DELETEUNIT                  1031
#define IDC_HEIGHTSTRENGTH              1031
#define IDC_CREATEUNIT2                 1032
#define IDC_SAVERESSET                  1032
#define IDC_SETNAME                     1032
#define IDC_EDIT2                       1032
#define IDC_RESSETNAME                  1032
#define IDC_EDIT3                       1033
#define IDC_CREATERESSET                1033
#define IDOK2                           1034
#define IDC_DELETERESSET                1034
#define IDC_DEPTH                       1035
#define IDC_BINDANI                     1035
#define IDC_WIDTH                       1036
#define IDC_CREATESUBUNIT               1036
#define IDC_CLASSVIEW                   1036
#define IDC_TREE2                       1037
#define IDC_BINDEFFECT                  1037
#define IDC_EFFECTVIEW                  1038
#define IDC_DELETERESSET2               1039
#define IDC_LOADRESSET                  1039
#define IDC_RESSETLIST                  1040
#define IDC_TRANSLUCENT                 1041
#define IDC_SOLID                       1042
#define IDC_TRANSLUCENT2                1043
#define IDC_TRANSVERTEX                 1043
#define IDC_SOLID2                      1044
#define IDC_TRANSTEXTURE                1044
#define ID_VIEW_HIDE                    32773
#define ID_EXPORTASCLIENT               32778
#define ID_EXPORTASSERVER               32779
#define ID_Menu                         32781
#define ID_SV                           32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
