--gas_require "relation/cofc/GasCofcBasicInc"
--
--local CofcBasicDB = "CofcBasicDB"
--
--------------------------------------------------------------------------------
----- @brief 创建商会
----- @param Conn,sucflag,result
--function CCofc:RequestCreateCofc(Conn,sucflag,result,cofcName)
--	if sucflag == false then
--		if result ~= nil then
--			MsgToConn(Conn, result)
--		end
--	else
--		Conn.m_Player.m_Properties:SetCofcID(result)--高速操作
--		Gas2Gac:RetRequestCreateCofc(Conn)
--	end
--end
----- @brief 创建商会
--function Gac2Gas:RequestCreateCofc(Conn, cofcName)
--	local playerId = Conn.m_Player.m_uID
--	local data = {
--					["playerId"] = playerId,
--					["cofcName"] = cofcName
--					}
--					
--	local function callback(sucflag,result)
--		CCofc:RequestCreateCofc(Conn,sucflag,result,cofcName)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "AddCofc", callback, data)
--end
--------------------------------------------------------------------------------------
----- @brief 退出商会
--function CCofc:LeaveCofc(Conn,result)
--	if IsNumber(result) then
--		MsgToConn(Conn, result)
--		return
--	end
--	Gas2Gac:ReturnLeaveCofc(Conn)
--end
--
----- @brief 退出商会
--function Gac2Gas:LeaveCofc(Conn)
--	local playerId = Conn.m_Player.m_uID
--	local data = {
--					["player_id"] = playerId,
--					}
--	local function callback(result)
--		CCofc:LeaveCofc(Conn,result)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "LeaveCofc", callback, data, Conn.m_Player.m_Properties:GetCofcID())
--end
--------------------------------------------------------------------------------------
--function CCofc:GetCofcInfo(Conn,info,position,memberCount,onlineMemberCount)
--	if info ~= nil then
--		-- c_sName, c_dtCreateTime, c_uLevel, c_uMoney, c_sPurpose
--		--要传回去的参数:自己的职位，商会名称，等级，资金，商业指数，在线商会人数，总人数，人气值，
--		--资源产量加成，上周商会盈利，本周商会盈利，杂物回收加成，目前正在升级科技名称， 现有科技等级，总科技等级，商会宗旨
--		Gas2Gac:RetGetCofcInfo(Conn, 
--			position or "", -- 自己的职位
--			info.c_sName.value,	-- 商会名称
--			info.c_uLevel.value, -- 等级
--			info.c_uMoney.value, -- 资金
--			0, -- 商业指数
--			onlineMemberCount, -- 在线商会人数
--			memberCount, -- 总人数
--			0, -- 人气值
--			0, -- 资源产量加成
--			0, -- 上周商会盈利
--			0, -- 本周商会盈利
--			0, -- 杂物回收加成
--			"无", -- 目前正在升级科技名称
--			0, -- 现有科技等级
--			0, -- 总科技等级
--			info.c_sPurpose.value) -- 商会宗旨
--		MsgToConn(Conn, 110074)-- "查询信息成功")
--	end
--end
----- @brief 得到商会的详细信息
--function Gac2Gas:GetCofcInfo(Conn, npc_id)
--	local playerId = Conn.m_Player.m_uID
--	local data = {
--					["npc_id"] = npc_id,
--					["playerId"] = playerId 
--					}
--					
--	local function callback(info,position,memberCount,onlineMemberCount)
--		CCofc:GetCofcInfo(Conn,info,position,memberCount,onlineMemberCount)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "GetCofcInfoSet", callback, data)
--end
--------------------------------------------------------------------------------------
--function CCofc:OpenCofCNpcDialog(Conn,result)
--	if result == false or result == nil then
--		return false
--	else
--		Gas2Gac:RetOpenCofCNpcDialogBegin(Conn)
--		if next(result) then
--			for i = 1, #result do
--				Gas2Gac:RetOpenCofCNpcDialog(Conn, result[i][1], result[i][2], result[i][3])
--			end
--		end
--		Gas2Gac:RetOpenCofCNpcDialogEnd(Conn)
--		return true
--	end
--end
----- @brief 得到商会列表
--function Gac2Gas:OpenCofCNpcDialog(Conn, npc_id)
--	local data = {
--					["npc_id"] = npc_id
--					}
--					
--	local function callback(result)
--		CCofc:OpenCofCNpcDialog(Conn,result)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "SendCofcList", callback, data)
--end
--------------------------------------------------------------------------------------
--function CCofc:ModifyCofcPropose(Conn,result)
--	if result then
--		Gas2Gac:RetModifyCofcPropose(Conn)
--		MsgToConn(Conn, 110025)
--	else
--		MsgToConn(Conn, 110026)
--	end
--end
----- @brief 修改商会宗旨
--function Gac2Gas:ModifyCofcPropose(Conn, propose)
--
--	local playerId = Conn.m_Player.m_uID
--	
--	local data = {
--					["player_id"] = playerId,
--					["propose"] = propose
--					}
--					
--	local function callback(result)
--		CCofc:ModifyCofcPropose(Conn,result)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "ModifyPurpose", callback, data, Conn.m_Player.m_Properties:GetCofcID())
--end
--------------------------------------------------------------------------------------
--function CCofc:GetCofCMembersInfo(Conn,memberList,requestList)
----发送商会会员列表开始.........
--	Gas2Gac:RetGetCofCMembersInfoBegin(Conn)
--	if memberList ~= nil and #memberList > 0 then
--		for i = 1, #memberList do
--			--角色id，角色名，商会中的职位，等级，种族，职业,心情寄语, 状态,心情，玩家是否在线
--			local uOnline = 2
--			if g_GetPlayerInfo(memberList[i][1]) ~= nil then
--				uOnline = 1
--			end
--			Gas2Gac:RetGetCurCofCMembersInfo(Conn,
--				memberList[i][1], memberList[i][2], memberList[i][3], memberList[i][4],memberList[i][5],
--				memberList[i][6], memberList[i][7], memberList[i][8],memberList[i][9],uOnline)
--		end
--	end
--	
----发送商会会员列表开始.........
--	Gas2Gac:RetGetCofCMembersInfoEnd(Conn,200)
--
----发送申请入会请求开始.........
--	Gas2Gac:RetGetCofCAppInfoBegin(Conn)
--	if next(requestList) then
--		for i = 1, #requestList do
--			Gas2Gac:RetGetCurCofCAppInfo(Conn,
--				requestList[i][1], requestList[i][2], requestList[i][3], 
--				requestList[i][4], requestList[i][5], requestList[i][6], requestList[i][7])
--		end
--	end
----发送申请入会请求结束.........
--	Gas2Gac:RetGetCofCAppInfoEnd(Conn,100)
--end
----- @brief 打开商会成员面板，得到相关信息
--function Gac2Gas:GetCofCMembersInfo(Conn)
--
--	local playerId = Conn.m_Player.m_uID
--	local data = {
--					["player_id"] = playerId,
--					}
--	local function callback(memberList,requestList)
--		CCofc:GetCofCMembersInfo(Conn,memberList,requestList)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "GetCofCMembersInfo", callback, data)
--end
--------------------------------------------------------------------------------------
--function CCofc:RequestJoinCofC(Conn,result)
--	if IsNumber(result) then
--		MsgToConn(Conn, result)
--	else
--		MsgToConn(Conn, 110028)
--		return ture
--	end
--end
----- @brief 申请加入商会，参数：商会id,自我描述
--function Gac2Gas:RequestJoinCofC(Conn, cofc_id, desc)
--
--	local playerId = Conn.m_Player.m_uID
--	local data = {
--					["player_id"] = playerId,
--					["cofc_id"] = cofc_id,
--					["desc"] = desc 
--					}
--	local function callback(result)
--		CCofc:RequestJoinCofC(Conn,result)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "RequestJoin", callback, data)
--end
--------------------------------------------------------------------------------------
--function CCofc:IntroduceJoinCofC(Conn,result)
--	if IsNumber(result) then
--		MsgToConn(Conn, result)
--	else
--		return ture
--	end
--end
----- @brief 引荐入会,参数：商会id
--function Gac2Gas:IntroduceJoinCofC(Conn, player_name, desc)
--local playerId = Conn.m_Player.m_uID
--	local data = {
--					["player_id"] = playerId,
--					["player_name"] = player_name,
--					["desc"] = desc 
--					}
--	local function callback(result)
--		CCofc:IntroduceJoinCofC(Conn,result)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "IntroduceJoin", callback, data, Conn.m_Player.m_Properties:GetCofcID())
--end
--------------------------------------------------------------------------------------
--function CCofc:ApproveJoinCofC(Conn,player_id,result1,result2,cofcId,cofcName)
--	if IsNumber(result1) then
--		MsgToConn(Conn, result1)
--	elseif result1 == false then
--		return false
--	else
--		if g_GetPlayerInfo(player_id) ~= nil then
--			g_GetPlayerInfo(player_id).m_Properties:SetCofcID(cofcId)--高速操作
--		end
--		CCofc:GetCofCMembersInfo(Conn,result1,result2)
--	end
--end
--
----- @brief 允许申请入会者加入商会，参数：玩家信息id
--function Gac2Gas:ApproveJoinCofC(Conn, player_id)
--	local self_Id = Conn.m_Player.m_uID
--	local data = {
--					["playerId"] = player_id,
--					["self_Id"] = self_Id,
--					}
--	local function callback(result1,result2,cofcId,cofcName)
--		CCofc:ApproveJoinCofC(Conn,player_id,result1,result2,cofcId,cofcName)
--	end
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "ApproveJoinCofC", callback, data, Conn.m_Player.m_Properties:GetCofcID())
--end
--------------------------------------------------------------------------------------
--function CCofc:RefuseJoinCofC(Conn,result1,result2)
--	if IsNumber(result1) then
--		MsgToConn(Conn, 110030)
--	elseif result1 == false then
--		return false
--	else
--		CCofc:GetCofCMembersInfo(Conn,result1,result2)
--	end
--end
----- @brief 拒绝申请入会者加入商会，参数：玩家信息id
--function Gac2Gas:RefuseJoinCofC(Conn, player_id)
--
--	local self_Id = Conn.m_Player.m_uID
--	local data = {
--					["playerId"] = player_id,
--					["self_Id"] = self_Id,
--					}
--	local function callback(result1,result2)
--		CCofc:RefuseJoinCofC(Conn,result1,result2)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "RefuseJoinCofC", callback, data, Conn.m_Player.m_Properties:GetCofcID())
--end
--------------------------------------------------------------------------------------
--function CCofc:ChangeCofCMemberPos(Conn,result1,result2)
--	if IsNumber(result1) then
--		MsgToConn(Conn, result1)
--	elseif result1 == true then
--		CCofc:GetCofCMembersInfo(Conn,result2,nil)
--	end
--end
----- @brief 修改会员职位,参数：玩家信息id，新的职位
--function Gac2Gas:ChangeCofCMemberPos(Conn, player_id, position)
--
--	local self_Id = Conn.m_Player.m_uID
--	local data = {
--					["playerId"] = player_id,
--					["self_Id"] = self_Id,
--					["position"] = position
--					}
--	local function callback(result1,result2)
--		CCofc:ChangeCofCMemberPos(Conn,result1,result2)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "ChangeCofCMemberPos", callback, data, Conn.m_Player.m_Properties:GetCofcID())
--end
--------------------------------------------------------------------------------------
--function CCofc:KickOutCofCMember(Conn,player_id,result)
--	if result ~= nil then
--		if IsNumber(result) then
--			MsgToConn(Conn, result)
--		else
--		if g_GetPlayerInfo(player_id) ~= nil then
--			g_GetPlayerInfo(player_id).m_Properties:SetCofcID(0)
--			Gas2Gac:RetKickOutCofCMember(g_GetPlayerInfo(player_id).m_Conn)
--		end
--		CCofc:GetCofCMembersInfo(Conn,result,nil)
--		end
--	end
--end
----- @brief 将商会成员踢出，参数:玩家信息id
--function Gac2Gas:KickOutCofCMember(Conn, player_id)
--	local self_Id = Conn.m_Player.m_uID
--	local data = {
--					["playerId"] = player_id,
--					["self_Id"] = self_Id,
--					}
--	local function callback(result)
--		CCofc:KickOutCofCMember(Conn,player_id,result)
--	end
--
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "KickOutCofCMember", callback, data, Conn.m_Player.m_Properties:GetCofcID())
--end
-----------------------------------------------------------------------------------------
--local function GetCofCLogInfo(Conn,tbl)
--	Gas2Gac:ReturnLogBegin(Conn)
--	if next(tbl) then
--		for i = 1, #tbl do
--			Gas2Gac:ReturnLog(Conn,
--				tbl[i][1], tbl[i][2],tbl[i][3])
--		end
--	end
--	Gas2Gac:ReturnLogEnd(Conn)
--end
----@brief 显示商会日志
--function Gac2Gas:GetCofCLogInfo(Conn,logType)
--	local self_Id = Conn.m_Player.m_uID
--	local data = {
--					["logType"] = logType,
--					["playerId"] = self_Id
--					}
--	local function callback(tbl)
--		GetCofCLogInfo(Conn,tbl)
--	end
--	--local CofcBasicDB = (g_DBTransDef["CofcBasicDB"])
--	CallAccountManualTrans(Conn.m_Account, CofcBasicDB, "GetLog", callback, data)
--end
--
