--gac_require "relation/tong/TongMyResOrderWndInc"
--
--------我的订单面板------
--
--function CreateTongMyResOrderWnd(Parent)
--	local Wnd = CTongMyResOrderWnd:new()
--	Wnd:Init(Parent)
--	return Wnd
--end
--
--function CTongMyResOrderWnd:Init(Parent)
--	self:CreateFromRes("TongMyResOrderWnd", Parent)
--	self:ShowWnd(false)
--	g_ExcludeWndMgr:InitExcludeWnd(self, 2, false, nil, 1)
--end
--
--function CTongMyResOrderWnd:OnChildCreated()
--	self.m_TongName = self:GetDlgChild("TongName")
--	self.m_Wz = self:GetDlgChild("Wz")
--	self.m_Wzs = self:GetDlgChild("Wzs")
--	self.m_Price = self:GetDlgChild("Price")
--	self.m_LeftNum = self:GetDlgChild("LeftNum")
--	self.m_OkBtn = self:GetDlgChild("OkBtn")
--	self.m_CancelBtn = self:GetDlgChild("CancelBtn")
--	self.m_XBtn = self:GetDlgChild("XBtn")
--end
--
--function CTongMyResOrderWnd:OpenPanel()
--	Gac2Gas:GetTongMyResOrderInfo(g_Conn)
--	self:ShowWnd(true)
--end
--
----消息
--function CTongMyResOrderWnd:OnCtrlmsg(Child, uMsgID, uParam1, uParam2)
--	if uMsgID == BUTTON_LCLICK then
--		if Child == self.m_XBtn then
--			self:ShowWnd(false)
--		elseif(Child == self.m_OkBtn) then
--			Gac2Gas:RequestAddTongBuyOrder(g_Conn)
--			self:ShowWnd(false)
--		elseif Child == self.m_CancelBtn then
--			Gac2Gas:CancelTongBuyOrder(g_Conn)
--			self:ShowWnd(false)
--		end
--	end
--end
--
--function CTongMyResOrderWnd:ShowMyResOrderInfo(TongName, Wz, Wzs, Price, LeftNum)
--	if TongName == "" then --用以判断取消订单
--		self.m_TongName:SetWndText("")
--		self.m_Wz:SetWndText("")
--		self.m_Wzs:SetWndText("")
--		self.m_Price:SetWndText("")
--		self.m_LeftNum:SetWndText("")
--		return
--	end
--	self.m_TongName:SetWndText(TongName)
--	self.m_Wz:SetWndText(Wz)
--	self.m_Wzs:SetWndText(Wzs)
--	self.m_Price:SetWndText(Price)
--	self.m_LeftNum:SetWndText(LeftNum)
--end