--
--CFixEquipWnd = class (SQRDialog)
--
--local function CreateFixEquipWnd(wnd)
--	wnd:CreateFromRes("FixEquipWnd", g_GameMain)
--	wnd:InitChild()
--	g_ExcludeWndMgr:InitExcludeWnd(wnd, "非互斥")
--end
--
--function CFixEquipWnd:Ctor()
--    CreateFixEquipWnd(self)
--end
--
--function CFixEquipWnd:InitChild()
--	self.m_CloseBtn = self:GetDlgChild("CloseBtn")
--	self.m_RenewEquip = self:GetDlgChild("RenewEquip")
--	self.m_RenewAllEquip = self:GetDlgChild("RenewAllEquip")
--	self.m_LeaveBtn = self:GetDlgChild("LeaveBtn")
--end
--
--local nAllPartNum = 13
--local function GetNeedMoneyToFixAll()
--    local totalNeedMoney = 0
--    for i = 1, nAllPartNum do
--        if g_GameMain.m_RoleStatus.Part[i].m_Info ~= nil then
--            local Info = g_GameMain.m_RoleStatus.Part[i].m_Info 
--			local nBigID,nIndex,nItemID = Info:GetBigID(),Info:GetIndex(),Info:GetItemID()
--			local DynInfo = g_DynItemInfoMgr:GetDynItemInfo(nItemID)
--			if tonumber(DynInfo.CurDuraValue) < tonumber(DynInfo.MaxDuraValue) then
--			    local needMoney = MoneyConsumedFixingEquip_Common(DynInfo.BaseLevel,"MoneyConsumed")
--			    totalNeedMoney = totalNeedMoney + needMoney
--			end
--	    end
--	end
--	return totalNeedMoney
--end
--
--function CFixEquipWnd:CheckMoneyEnoughForFixingEquip(curMoneyType, needMoney)
--    local function callback(Context,Button)
--        if Button == MB_BtnOK then
--            if curMoneyType == 1 then
--                if needMoney > g_MainPlayer.m_nBindMoney  then
--                    self.m_MsgBox = MessageBox(self, MsgBoxMsg(1018), MB_BtnOK)
--                else
--                    curMoneyType = 2
--                    self:LockOrOnLockPosInBag(false)
--                    Gac2Gas:RenewAllEquipDuraValue(g_Conn, curMoneyType)        	            
--                end
--            else
--                if needMoney > g_MainPlayer.m_nMoney  then
--                    self.m_MsgBox =MessageBox(self, MsgBoxMsg(1018), MB_BtnOK)
--                else
--                    curMoneyType = 1
--                    self:LockOrOnLockPosInBag(false)
--                    Gac2Gas:RenewAllEquipDuraValue(g_Conn, curMoneyType)     	            
--                end
--            end            
--        end
--        return true
--    end
--    if curMoneyType == 1 then --当前选择的是流通的金币
--        if needMoney > g_MainPlayer.m_nMoney then
--            self.m_MsgBox =MessageBox(self, MsgBoxMsg(1017), BitOr( MB_BtnOK, MB_BtnCancel), callback)
--        else
--            self:LockOrOnLockPosInBag(false)
--            Gac2Gas:RenewAllEquipDuraValue(g_Conn, curMoneyType)
--        end
--    else
--        if needMoney > g_MainPlayer.m_nBindMoney then
--            self.m_MsgBox =MessageBox(self, MsgBoxMsg(1017), BitOr( MB_BtnOK, MB_BtnCancel), callback)
--        else
--            self:LockOrOnLockPosInBag(false)
--            Gac2Gas:RenewAllEquipDuraValue(g_Conn, curMoneyType)  
--        end
--    end
--end
--
--function CFixEquipWnd:OnCtrlmsg(Child, uMsgID, uParam1, uParam2)
--	if uMsgID == BUTTON_LCLICK then
--		if Child == self.m_CloseBtn or Child == self.m_LeaveBtn then
--			self:ShowWnd(false)
--		elseif Child == self.m_RenewEquip then
--			g_WndMouse:SetRenewEquip()
--		elseif Child == self.m_RenewAllEquip then
--		    if g_MainPlayer.m_ItemBagLock then
--                MsgClient(160045)
--                return
--            end
--		    self:ClearFixEquipState()
--		    local curMoneyType = g_MainPlayer:GetMoneyType()
--		    local needMoneyToFixInRole = GetNeedMoneyToFixAll()
--		    self.m_NeedLockPosInBagTbl = {}
--		    local needMoneyToFixInBag 
--		    needMoneyToFixInBag, self.m_NeedLockPosInBagTbl = g_GameMain.m_WndMainBag.m_ctItemRoom:GetMoneyToFixDemagedEquipInBag()
--		    local needMoneyToFix = needMoneyToFixInRole + needMoneyToFixInBag
--		    if needMoneyToFix == 0 then
--               self.m_MsgBox = MessageBox(self, MsgBoxMsg(1020), MB_BtnOK) 
--		       return 
--		    end
--		    local c_money = CMoney:new()
--            local moneyNeedToFixStr = c_money:ChangeMoneyToString(needMoneyToFix)
--            local function callback(Context,Button)
--                if Button == MB_BtnOK then
--                    self:CheckMoneyEnoughForFixingEquip(curMoneyType, needMoneyToFix)
--                end
--                return true
--            end
--            self.m_MsgBox =MessageBox(self, MsgBoxMsg(1019, moneyNeedToFixStr), BitOr( MB_BtnOK, MB_BtnCancel), callback) 
--		end
--	end
--end
--
--function CFixEquipWnd:LockOrOnLockPosInBag(bFlag)
--    if self.m_NeedLockPosInBagTbl == nil then
--        return
--    end 
--    for i, v in pairs(self.m_NeedLockPosInBagTbl) do
--        local roomIndex = v[1]
--        local pos = v[2]
--        local SrcCt = g_GameMain.m_BagSpaceMgr:GetSpaceRelateLc( roomIndex )
--        local y, x = SrcCt:GetIndexByPos(pos, roomIndex)
--	    SrcCt:SetClickedWndState(x, y, roomIndex, bFlag)
--    end
--end
--
--function CFixEquipWnd:VirtualExcludeWndClosed()
--	local state = g_WndMouse:GetCursorState()
--	if state == ECursorState.eCS_RenewEquip then
--		g_WndMouse:ClearCursorSpecialState()
--	end
--	g_GameMain.m_RoleStatus:UpdataEquipTips()
--	g_GameMain.m_WndMainBag.m_ctItemRoom:UpdateBagTips()
--    self:ClearFixEquipState()
--end
--
--function CFixEquipWnd:ClearFixEquipState()
--    g_WndMouse:ReleaseCursorLock()
--    g_WndMouse:SetCursorSkillState( ECursorSkillState.eCSS_Normal )
--    g_WndMouse:ClearCursorAll()	
--end
--
--function CFixEquipWnd.RetRenewEquipSuc(equipPart, equipType, equipName, equipID)
--    if equipPart ~= 0 then
--        if g_ItemInfoMgr:IsStaticWeapon(equipType) then
--            if  equipPart == EEquipPart.eWeapon then
--                g_MainPlayer:SetWeaponVisible(true, true)
--            elseif equipPart == EEquipPart.eAssociateWeapon then
--                g_MainPlayer:SetWeaponVisible(false, true)
--            end
--        end    
--    end
--end
--
--function CFixEquipWnd.RenewAllEquipEnd()
--    g_GameMain.m_FixEquipWnd:LockOrOnLockPosInBag(true)
--    g_GameMain.m_FixEquipWnd.m_NeedLockPosInBagTbl = nil
--end
--
