engine_require "common/Script/ExportClass"

local ExportTbl = 
{
	{"CAutoCloseWnd", "activity/ClientAutoCloseWnd/ClientAutoCloseWnd"},
	{"CCountdownWnd", "activity/CountDownWnd/CountDownWnd"},
	{"CAreaFbInfoWnd", "activity/AreaFbWnd/AreaFbInfoWnd"},
	{"CAreaFbListWnd", "activity/AreaFbWnd/AreaFbListWnd"},
	{"CObjShowContent", "activity/obj_showcontent/ObjShowContent"},
	{"CGMActivityWnd", "activity/gm_compensate/GMActivityWnd"},
	{"CGMCompensateWnd", "activity/gm_compensate/GMCompensateItemWnd"},
	{"CTransportWnd", "activity/TransportWnd/TransportWnd"},
	{"CAgiotage", "commerce/agiotage_wnd/Agiotage"},
	--副本相关
	{"CFbActionMsgWnd", "activity/fb_action/FbActionMsgWnd"},
	{"CLingYuTransmitWnd", "activity/fb_action/lingyu_wnd/LingYuTransmitWnd"},
	{"CJuQingTransmitWnd","activity/fb_action/juqing_wnd/JuQingTransmitWnd"},
	{"CFbActionQueueWnd", "activity/fb_action/FbActionQueueWnd"},
	{"CFbGameStatisticsWnd", "activity/fb_action/FbGameStatisticsWnd"},
	{"CDpsOutPutWnd", "activity/fb_action/juqing_wnd/DPSOutPutWnd"},
	{"CJiFenSaiInfoWnd", "activity/JiFenSaiInfoWnd/JiFenSaiInfoWnd"},
	{"CDaDuoBaoWnd", "activity/fb_action/join_fb_wnd/DaDuoBaoWnd"},
	{"CDownTimeWnd", "activity/fb_action/into_fb_wnd/daduobao_wnd/DownTimeWnd"},
	{"CCountdown", "activity/fb_action/countdown_wnd/CountdownWnd"},
	{"CDaTaoShaWnd", "activity/fb_action/join_fb_wnd/DaTaoShaWnd"},
	{"CJiFenSaiWnd", "activity/fb_action/join_fb_wnd/JiFenSaiWnd"},
	{"CBossBattleWnd", "activity/fb_action/BossBattleWnd"},
	{"CTempBagWnd", "activity/fb_action/temp_bag_wnd/TempBagWnd"},
	{"CMercCardWnd", "activity/fb_action/mercenary_eduact_wnd/MercCardWnd"},
	{"CMercCardBagWnd", "activity/fb_action/mercenary_eduact_wnd/MercCardBagWnd"},
	{"CMercCardPageOneWnd", "activity/fb_action/mercenary_eduact_wnd/MercCardPageOneWnd"},
	{"CMercCardPageTwoWnd", "activity/fb_action/mercenary_eduact_wnd/MercCardPageTwoWnd"},
	{"CFbActionPanelWnd", "activity/quest/FbActionPanel"},
	{"CFbActionPanelItemWnd", "activity/quest/FbActionPanelItemWnd"},
	{"CYbEducateActionAwardWnd", "activity/fb_action/mercenary_eduact_wnd/YbEducateActionAwardWnd"},
	{"CYbEducateActionInfoWnd", "activity/fb_action/mercenary_eduact_wnd/YbEducateActionInfoWnd"},
	{"CYbEducateActionWnd", "activity/fb_action/mercenary_eduact_wnd/YbEducateActionWnd"},
	{"CYbEduActScoreInfoWnd", "activity/fb_action/mercenary_eduact_wnd/ScoreInfoWnd"},
	{"CAreaFbSelWndNew", "activity/AreaFbWnd/NewAreaFbSelWnd" },
	{"CShootProgressWnd", "activity/fb_action/DrinkShoot"},
	{"CDragonCaveWnd", "activity/fb_action/DragonCaveWnd"},
	
	{"CFbDPSWnd", "activity/fb_action/DPSWnd"},
	
	--MatchGame副本
	{"CMatchGameCountWnd", "activity/fb_action/match_game_wnd/MatchGameCountWnd"},
	{"CMatchGameSelWnd", "activity/fb_action/match_game_wnd/MatchGameSelWnd"},
	{"CConfirmWnd", "activity/fb_action/ConfirmItemWnd"},
	{"CConfirmSecWnd", "activity/fb_action/ConfirmItemSecWnd"},
	
	------information------
	--中地图相关
	{"CWarZoneStateBtn", "information/area_map/WarZoneStateBtn"},
	{"CAreaInfoWnd", "information/area_map/AreaInfoWnd"},
	{"CScenePictureWnd", "information/area_map/ScenePictureWnd"},	
	{"CNpcPointBtnWnd", "information/area_map/NpcPointBtnWnd"},	
	{"CAreaSelectTypeListItemWnd", "information/area_map/AreaSelectTypeListItemWnd"},
	{"CAreaSubMenuWnd", "information/area_map/AreaSubMenuWnd"},
	{"CTeammateBtnWnd", "information/area_map/TeammateBtnWnd"},
	{"CTongmateBtnWnd", "information/area_map/TongmateBtnWnd"},
	{"CFbPlayerBtnWnd", "information/area_map/FbPlayerBtnWnd"},
	{"CGuideBtn", "information/guide/GuideBtn"},
	{"CGuide", "information/guide/Guide"},
	{"CGuideData", "information/guide/GuideData"},
	--排行榜
	{"CSortList", "information/sort_list/SortList"},
	-----------------------
	
	--任务相关
	{"CQuestPoolWnd", "activity/questpool_wnd/QuestPoolWnd"},
	{"CTakeTaskWnd", "activity/quest/TakeQuest"},
	{"CFinishTaskWnd", "activity/quest/FinishQuest"},
	{"CShareQuestWnd", "activity/quest/ShareQuest"},
	{"CQihunjiZhiyinWnd", "activity/quest/QihunjiZhiyinWnd"},
	{"CHeadHelpWnd", "activity/quest/HeadHelpWnd"},
	{"CHandBookWnd", "activity/quest/HandBookWnd"},
	--{"CMercenaryLevelAward", "activity/MercenaryLevelWnd/MercenaryLevelAward"},
	{"CYBDirTempFxWnd", "activity/mercenary_direction/Yb_Dir_Wnd"},
	--{"CYbAssessWnd", "activity/mercenary_direction/Yb_Assess_Wnd"},
	{"CNpcTalkWnd", "activity/NpcTalkWnd/NpcTalkWnd"},
	{"CGamePromptWnd", "activity/GamePromptWnd/GamePromptWnd"},
	{"CInformationWnd", "activity/NpcTalkWnd/InformationWnd"},
	
	
	{"AutoTrackerHandlerForNpc", "character/auto_tracker/AutoTrackerHandlerForNpc"},
	{"AutoTrackerHandlerForDeadNpc", "character/auto_tracker/AutoTrackerHandlerForDeadNpc"},
	{"AutoTrackerHandlerForIntObj", "character/auto_tracker/AutoTrackerHandlerForIntObj"},
	{"AutoTrackerHandlerForFollowingPlayer", "character/auto_tracker/AutoTrackerHandlerForFollowingPlayer"},
	{"CCharacterInSyncMgr", "character/character_in_sync_mgr/CharacterInSyncMgr"},
	{"CCharacterInViewMgr", "character/character_in_view_mgr/CharacterInViewMgr"},
	{"CCharacterClientCallbackHandler", "character/CharacterClientCallbackHandler"},
	{"CEntityClientMgrHandler", "character/CharacterClientMgrHandler"},
	{"CCharacterDirector", "character/CharacterDirector"},
	{"CCharacterDirectorCallbackHandler", "character/CharacterDirectorCallbackHandler"},
	{"CCharacterFollower", "character/CharacterFollower"},
	{"CCharacterFollowerCallbackHandler", "character/CharacterFollowerCallbackHandler"},
	{"CIntObjCallbackHandler", "world/int_obj/IntObjCallbackHandler"}, 
	
	{"CFightInfoWnd", "fight/skill_wnd/FightInfo"},
	{"CStonePart", "item/stone/StonePart"},
	{"CStone", "item/stone/Stone"},
	{"CStoneCompound", "item/stone/StoneCompound"},
	{"CWhiteStone", "item/stone/WhiteStone"},
	{"CBaseInfo", "fight/servant_info/BaseInfo"},
	{"CServantInfo", "fight/servant_info/ServantInfo"},
	{"CBattleHorseInfo", "fight/servant_info/BattleHorseInfo"},
	{"CCannonInfo", "fight/servant_info/Cannon"},
	{"COrdnanceMonsterInfo", "fight/servant_info/OrdnanceMonsterInfo"},
	{"CTruckInfo", "fight/servant_info/TruckInfo"},
	{"CChangeNameWnd", "fight/servant_info/ChangeNameWnd"},
	{"CBaseServantBuffWnd", "fight/servant_info/ServantBuff"},
	{"CBuffWnd", "fight/buff_wnd/BuffWnd"},
	{"CPlayerBuffWnd", "fight/buff_wnd/PlayerBuff"},
	{"CTargetBuffWnd", "fight/buff_wnd/TargetBuff"},
	{"CTargetOfTargetBuffWnd", "fight/buff_wnd/TargetOfTargetBuff"},
	{"CTeammateBuff", "fight/buff_wnd/TeammateBuff"},
	{"CStatisticFightInfoWnd", "fight/skill_wnd/StatisticFightInfo"},
	{"CFighterViewInfoMgr", "fight/fighterview_info_mgr/FighterViewInfoMgr"},
	{"CHideFollowerMgr", "toolbar/hide_player/HideFollowerMgr"},
	--pk 相关
	{"CPkSwitch", "character/pk_switch/PkSwitchWnd"},
	{"CPkSwitchMsg", "character/pk_switch/PkSwitchMsgWnd"},
	{"CTongForageWnd", "relation/tong/TongForageWnd"},
	{"CWarTransportWnd", "relation/tong/TongWarTransportWnd"},
	{"CTongForageSeekWnd", "relation/tong/TongForageSeekWnd"},
	{"CSeekInfoWnd", "relation/tong/TongSeekInfoWnd"},
	{"CTongIssueFetchWnd", "relation/tong/TongIssueFetchWnd"},
	{"CIssueWnd", "relation/tong/TongIssueWnd"},
	{"CTongCancelSignWnd", "relation/tong/TongCancelSignWnd"},
	{"CTongEnterSceneWnd", "relation/tong/TongEnterSceneWnd"},
	{"CConfirmJoinWnd", "relation/tong/TongConfirmJoinWnd"},
	
	--特殊Npc
	{"CSpecialNpcWnd", "activity/npc_dialog_box/SpecialNpcWnd"},
	{"CCreateListCtrlItemWnd", "activity/npc_dialog_box/SpecialCreateCtrlItemWnd"},
	{"CSpecialNpc_DialogBox", "activity/npc_dialog_box/SpecialNpc_DialogBox"},
	
	--播放声音
	{"CPlaySoundMgr", "activity/sound/PlaySoundMgr"},
	{"CPlaySoundOfWarning","activity/sound/PlaySoundOfWarning"},
	--复活窗口
	{"CTeamPVPFBDeadMsgWnd", "character/rebornwnd/TeamPVPFBDeadWnd"},
	{"CWndDeadMsg", "character/rebornwnd/WndCharDead"},
	{"CAreaFbDeadMsgWnd", "character/rebornwnd/AreaFbDeadWnd"},
	{"CRobResDeadMsgWnd", "character/rebornwnd/RobResDeadMsgWnd"},
	{"CWarDeadMsgWnd", "character/rebornwnd/WarDeadMsgWnd"},
	{"CChallengeDeadMsgWnd", "character/rebornwnd/ChallengeDeadMsgWnd"},
	{"CFBDeadMsgWnd", "character/rebornwnd/FBDeadMsgWnd"},
	{"COldWarDeadWnd", "character/rebornwnd/OldWarDeadWnd"},
	
	{"CComboHitsWnd","message/combohits_Wnd/ComboHitsWnd"},
	
	{"CEquipDuraWnd", "item/equip/equip_dura/EquipDura"},
--	{"CFixEquipWnd", "item/equip/fix_equip/FixEquip"},
	{"CNewFixEquipWnd", "item/equip/new_fixequip/NewFixEquip"},
	{"CEquipInRoleWnd", "item/equip/new_fixequip/EquipInRoleWnd"},
	{"CEquipInBagWnd", "item/equip/new_fixequip/EquipInBagWnd"},
	{"CJiFenWnd", "commerce/jifen_wnd/JiFenWnd"},
	{"CSmallMapSelectShowWnd", "information/small_map/SmallMapSelectWnd"},
	{"CSmallMapWnd", "information/small_map/SmallMapWnd"},
	{"CSmallMapBG", "information/small_map/SmallMapBGWnd"},
	{"CFightingEvaluation","fight/role_status/FightingEvaluation"},
	{"CAppellationAndMoralWnd","fight/role_status/AppellationAndMoral"},
	{"CRoleLevelUp","fight/role_status/RoleLevelUpAttention"},
	{"CLoginWaitingQueue","entrance/login/LoginWaitingQueue"},
	{"CAimFightingEvaluation","fight/role_status/AimFightingEvaluation"},
	
	------分配模式------
	--需求分配
	{"CNeedAssignWnd", "activity/assign_mode/NeedAssignWnd"},
	{"CAuctionAssignWnd", "activity/assign_mode/AuctionAssignWnd"},
	{"CChangeAuctionBasePrice","activity/assign_mode/ChangeAuctionBasePriceWnd"},
	--OBJ拾取
	{"CCollObjShowWnd", "activity/collobj_showwnd/CollObjShowWnd"},
	--插旗挑战
	{"CShowMessageWnd", "activity/challenge/ChallengeWnd"},
	{"CWaitAcceptChallengeWnd", "activity/challenge/WaitAcceptChallengeWnd"},
	{"CChallengeCompass", "activity/challenge/CreateSmallArrow"},
	{"CLoading", "entrance/loading/Loading"},
	
	--邮件
	{"CEmailBoxWnd", "message/email/email_main_wnd/EmailBoxWnd"},
	{"CEMailItemWnd", "message/email/email_main_wnd/EmailItemWnd"},
	{"CWndEmailMSG", "message/email/email_main_wnd/EmailMsgWnd"},
	{"CSendEmailWnd", "message/email/send_email_wnd/SendEmailWnd"},
	{"CReceiveImagineList", "message/email/send_email_wnd/ReceiveImagineList"},
	{"CFriendsListWnd", "message/email/send_email_wnd/FriendsListWnd"},
	{"CGetEmailWnd", "message/email/get_email_wnd/GetEmailWnd"},
	{"CMailTextAttachWnd", "message/email/get_email_wnd/MailTextAttachWnd"},
	{"CMailRpc", "message/email/MailRpc"},
	
	--背包
	{"CItemInGrid",				"item/bag_space_mgr/ItemInGrid"},
	{"CBagSpace",				"item/bag_space_mgr/BagSpace"},
	{"CBagSpaceMgr",			"item/bag_space_mgr/BagSpaceMgr"},
	{"CDynItemInfoMgr",			"item/bag_space_mgr/GacDynItemInfoMgr"},
	{"CGrid",					"item/bag_space_mgr/Grid"},
	{"CItem",					"item/bag_space_mgr/Item"},
	{"CStoreRoomWndMgr",		"item/wnd_item_bag/StoreRoomWndMgr"},
	{"CBreakItemWnd",			"item/wnd_item_bag/WndBreakItem"},
	{"CWndItemMainBag",			"item/wnd_item_bag/WndItemBag"},
	{"CWndSplit",				"item/wnd_item_bag/WndSplit"},
	{"CWndBagSlots",			"item/wnd_item_bag/WndBagSlot"},
	{"CUseItemRpcMgr",			"item/item_rpc/UseItemRpcMgr"},
	{"CBreakItemRpc",			"item/item_rpc/BreakItemRpc"},
	{"CMoneyRpc",				"item/item_rpc/MoneyRpc"},
	{"CRoomItemRpc",			"item/item_rpc/RoomItemRpc"},
	{"CDepot",					"item/depot/Depot"},
	
	--佣兵团
	{"CTongMainWnd", "relation/tong/tong_main_panel/TongMain"},
	{"CTongMemberWnd", "relation/tong/tong_main_panel/TongMember"},
	{"CTongMemberAppWnd", "relation/tong/tong_main_panel/TongMemberApp"},
	{"CTongPurviewWnd", "relation/tong/tong_main_panel/TongPurview"},
	{"CTongLogWnd", "relation/tong/tong_main_panel/TongLog"},
	{"CTongPrivilegeWnd", "relation/tong/tong_main_panel/TongPrivilege"},
	{"CTongHandBookWnd", "relation/tong/tong_main_panel/TongHandBook"},
	{"CTongMainPanWnd", "relation/tong/tong_main_panel/TongMainPan"},
	{"CTongBuildingItemCreateWnd", "relation/tong/tong_building/TongBuildingItemCreate"},
	{"CTongProductionCenterWnd", "relation/tong/tong_building/TongProductionCenter"},
	{"CTongDepotWnd", "relation/tong/tong_building/TongDepot"},
	{"CTongScienceWnd", "relation/tong/tong_building/TongScience"},
	{"CTongLearnScience","relation/tong/TongLearnScienceWnd"},
	{"CTongSellForageWnd", "relation/tong/TongSellForageWnd"},
	{"CTongForageQueryWnd", "relation/tong/TongForageQueryWnd"},
	{"CSignQueryWnd", "relation/tong/TongSignQueryWnd"},
	{"CRobResCountDown", "relation/tong/RobResCountDown"},
	{"CRobResourceWnd", "relation/tong/TongRobResourceWnd"},
	{"CTongRobOverExit", "relation/tong/TongRobOverExit"},
	{"CTongItemUseTrans", "relation/tong/TongItemUseTrans"},
	{"CTongRobResExitWnd", "relation/tong/TongRobResExitWnd"},
	{"CTongTypeChangeWnd", "relation/tong/tong_main_panel/TongTypeChange"},
	{"CTongTypeUpdateWnd", "relation/tong/tong_main_panel/TongTypeUpdate"},
	{"CTongChangeNameWnd", "relation/tong/TongChangeNameWnd"},
	{"CTongFetchResWnd", "relation/tong/TongFetchResWnd"},
	{"CShowRulesWnd", "relation/tong/TongShowRulesWnd"},
	{"CEssayQuestionWnd", "activity/essayquestionwnd/EssayQuestionWnd"},
	{"CArmyCorpsChangeName","relation/army_corps/ArmyCorpsChangeName"},
	{"CTongContributeMoneyWnd","relation/tong/TongContributeMoney"},
	{"CTongWarBattleAwardWnd","relation/tong/TongWarBattleAwardWnd"},
	{"CTongRecruit","relation/tong/TongRecruit"},
	{"CTongChangeByPos", "relation/tong/TongChangeByPosWnd"},
	
	-- 中地图
	--{"CFbPlayerBtnWnd", "information/area_map/FbPlayerBtnWnd"},
	
	--读条窗口
	{"CNormalProgressBarWnd", "activity/progress_bar_wnd/NormalProgressBarWnd"},
	{"CProgressBarWnd", "activity/progress_bar_wnd/ProgressBarWnd"},
	{"CUseItemProgressWnd", "activity/progress_bar_wnd/UseItemProgressWnd"},
	{"CXLProgressWnd", "activity/progress_bar_wnd/XLProgressWnd"},
	{"CSandGlassWnd", "activity/progress_bar_wnd/SandGlassWnd"},
	
	--进入矿洞副本提示
	{"COreSceneMSG", "activity/area_scene_wnd/OreAreaSceneWnd"},
	--花卉
	{"CFlowerWnd", "resource/gather_liveskill/CultivateFlowersWnd"},
	{"CFlowerMiniWnd", "resource/gather_liveskill/FlowerMiniWnd"},
	{"CShowGatherItemsWnd", "resource/gather_liveskill/ShowGatherItemsWnd"},
	
	------message------
	--变形消息提示框
	{"CMessageShapeEffectWnd","message/message_shapeeffect_wnd/MessageShapeEffectWnd"},
	{"CMessageShapeEffectSecondWnd","message/message_shapeeffect_wnd/MessageShapeEffectSecondWnd"},
	{"CMessageMiniTextWnd","message/message_shapeeffect_wnd/MessageMiniTextWnd"},
	{"CRollIntoMsg", "message/message_box/RollIntoMsg"},
	{"CSystemFriendMsgBox", "message/message_box/SystemFriendMsgBox"},
	{"CCenterMsg", "message/message_box/CenterMsg"},
	------------------
	
	{"CUserAgreement", "entrance/agreement/Agreement"},
	{"CUserAgreementWnd", "entrance/agreement/AgreementWnd"},
    
    {"CExitGame", "setting/exit_game/ExitGame"},
    {"WndExitMSG", "setting/exit_game/WndExitMsg"},
	{"CWndExitMSGAntiIndu", "setting/exit_game/WndExitMsgAntiIndu"},
    {"WndToLoginMsg", "setting/exit_game/WndToLoginMsg"},
	{"CBeastPoseWnd","fight/skill_wnd/BeastPoseWnd"},
    
    {"CTradeRequestTipsWnd", "commerce/players_trade/TradeInvitationTipWnd"},
    {"CTradeInvitationWnd", "commerce/players_trade/TradeInvitation"},
    {"CPlayerTradeRequestWnd", "commerce/players_trade/TradeRequest"},
    {"CPlayersTradeWnd", "commerce/players_trade/PlayersTrade"},
    
    {"CConsignmentSellListWnd", "commerce/consignment/ConsignmentSellList"},
    {"CConsignmentTreeListMap", "commerce/consignment/CSMTreeListMap"},
    {"CConsignmentSellListItemWnd", "commerce/consignment/ConsignmentSellListItem"},
    {"CTreeCtrlNode", "framework/TreeCtrl/CTreeCtrl"},
    {"CConsignmentSellItemItemWnd", "commerce/consignment/ConsignmentSellItemItem"},
    {"CConsignmentCommon", "commerce/consignment/ConsignmentCommon"},
    {"CConsignmentSellItemWnd", "commerce/consignment/ConsignmentSellItem"},
    
    {"CBuyBacthWnd", "commerce/npc_shop/NPCShopBatchWnd"},
    {"CNPCShopSellWnd", "commerce/npc_shop/NPCShopSell"},
    {"CNPCShopPlayerSoldWnd", "commerce/npc_shop/NPCShopPlayerSold"},
    {"CEquipUpIntensify","fight/role_status/EquipFetch"}, 
    {"CFlashMsgWnd","message/flash_message_wnd/FlashMsg"},
    {"CFlashSkillMsgWnd","message/flash_message_wnd/FlashSkillMsg"},
    
    {"CToolsMallMainWnd","commerce/tools_mall/ToolsMallMainWnd"},
    {"CToolsMallCommonWnd","commerce/tools_mall/ToolsMallCommon"},  
    {"CToolsMallBuyWnd","commerce/tools_mall/ToolsMallBuyWnd"},
    {"CToolsMallGiveItemWnd","commerce/tools_mall/ToolsMallGiveItemWnd"},
    {"CToolsMallHotSellListItemWnd","commerce/tools_mall/ToolsMallHotSellListItem"},
    {"CToolsMallSellListItemWnd","commerce/tools_mall/ToolsMallSellListItem"},
    {"CToolsMallShowYongBingBiWnd","commerce/tools_mall/ToolsMallShowMoneyWnd"},
    {"CToolsMallTakeMoneyWnd","commerce/tools_mall/ToolsMallTakeMoney"},
    
	{"CLoginAccounts", "entrance/login/LoginWnd"},
	{"CLogin", "entrance/login/Login"},
	{"CLoginCancelMsgBox", "entrance/login/LoginCancelMsgBox"},
	{"CLoginCancelMsgBoxHook", "entrance/login/LoginCancelMsgBoxHook"},
	{"CLoginHook", "entrance/login/LoginHook"},
	{"CSelectCamp", "entrance/select_char/SelectCamp"},
	{"CSelectCharState", "entrance/select_char/SelectChar"},
	{"CSelectCharWnd", "entrance/select_char/SelectCharWnd"},
	{"CWndDelRole", "entrance/select_char/DelChar"},
	{"CPlayerChangeNameWnd", "entrance/select_char/PlayerChangeNameWnd"},
	{"CSelectRoleIAccelerator", "entrance/select_char/SelectAccelerator"},
	{"CDelRoleList", "entrance/select_char/DelRoleList"},
	{"CScreenMask", "entrance/select_char/ScreenMask"},
	{"CLoginBackBtn", "entrance/select_char/LoginBackBtn"},
	
	{"CNewRoleEnterGame", "entrance/create_char/NewRoleEnterGame"},
	{"CNewRoleState", "entrance/create_char/NewRole"},
	{"CNewRoleWnd", "entrance/create_char/NewRoleWnd"},
	{"CClassIntroVideo", "entrance/create_char/ClassIntroVideo"},
	
	{"CEquipAssessWnd","fight/role_status/EquipAssessWnd"},
	{"CImageMgr","framework/Image_mgr/ImageMgr"},
	
	--佣兵团
	{"CArmyCorpsPanel","relation/army_corps/ArmyCorpsPanel"},
	{"CArmyCorpsMain","relation/army_corps/ArmyCorpsMain"},
	{"CArmyCorpsTeamInfo","relation/army_corps/ArmyCorpsTeamInfo"},
	{"CArmyCorpsMember","relation/army_corps/ArmyCorpsMember"},
	{"CArmyCorpsChangePosWnd","relation/army_corps/ArmyCorpsChangePos"},
	
	{"CPlayerManageWnd","fight/role_status/PlayerManageWnd"},
	{"CAimPlayerManageWnd","fight/role_status/AimPlayerManageWnd"},
	{"CContractManufactureMarketWnd", "commerce/ContractManufacture/ContractManufactureMarket"},
	{"CContractManufactureOrderWnd", "commerce/ContractManufacture/ContractManufactureOrder"},
	{"CContractManufactureCommon", "commerce/ContractManufacture/ContractManufactureCommon"},
	{"CContractManufactureOrderItemWnd", "commerce/ContractManufacture/ContractManufactureOrderItem"},
	{"CContractManufactureCharOrderItemWnd", "commerce/ContractManufacture/ContractManufactureCharOrderItem"},
	{"CContractManufactureMarketOrderItemWnd", "commerce/ContractManufacture/ContractManufactureMarketOrderItemWnd"},
	{"CAfflatusValueWnd","activity/afflatusvalue/CAfflatusValueWnd"},
	{"CLeadLeanSkillWnd","fight/skill_wnd/LeadLeanSkillWnd"},
	{"CLeadLeanSkillShowWnd","fight/skill_wnd/LeadLeanSkillShowWnd"},
	{"CTalentSkillDescWnd","fight/skill_wnd/TalentSkillDescWnd"},
	{"CEquipRefine", "item/equip/equip_refine/EquipRefine"},
    {"CNpcShopMsgWnd", "commerce/npc_shop/NpcShopMsgWnd"},
    {"NpcShopWndMsgSettingLiuTongBtn", "commerce/npc_shop/NpcShopWndMsgSettingLiuTongBtn"},
	{"CSkillJingLingWnd","fight/skill_wnd/JingLingSkill"},
	{"CLearnCommonSkillWnd","fight/skill_wnd/LearnCommonSkillWnd"},
	{"CNonFightSkill", "fight/skill_wnd/NonFightSkill"},
	{"CNpcSkillLearnWnd","fight/skill_wnd/NpcSkillLearnWnd"},
	{"CSelectSeriesWnd","fight/skill_wnd/SelectSeriesWnd"},
	{"CCommonSkillWnd","fight/skill_wnd/CommonSkillWnd"},
	{"CTalentSkillPartWnd","fight/skill_wnd/TalentSkillPartWnd"},
	{"CCommerceCommon","commerce/CommerceCommon"},
	{"CArmorPieceEnactment","item/equip/equip_relating/GacArmorPieceEnactment"},
	{"CEquipSmeltSoulScroll","item/equip/equip_relating/GacEquipSmeltSoulScroll"},
	{"GacEquipIdentify","item/equip/equip_relating/GacEquipIdentify"},	
	{"CAimStatus","fight/role_status/AimState"},
	{"CPlayerStatus","fight/role_status/PlayerState"},
	{"CHortationInfoWnd","fight/hortation/HortationInfo"},
	
	{"CEquipSuitTipWnd", "item/equip/equip_suit_tip/EquipSuitTip"},
	{"CItemBagLockWnd", "item/wnd_item_bag/ItemBagLockWnd"},
	{"CIdentityAffirmWnd", "item/wnd_item_bag/IdentityAffirmWnd"},
	{"CEquipSuperaddWnd", "item/equip/equip_superadd/EquipSuperadd"},
	{"CItemBagTimeLockWnd", "item/wnd_item_bag/ItemBagTimeLockWnd"},
	
	{"CPurchasingWnd","commerce/consignment/PurchasingWnd"},
	{"CPurchasingAgentMainWnd","commerce/consignment/PurchasingAgentMainWnd"},
	{"CPurchasingAgentSellWnd","commerce/consignment/PurchasingAgentSellWnd"},
	{"CPurchasingAgentQuickSellWnd","commerce/consignment/PurchasingAgentQuickSellWnd"},
	
  	{"CWithOneJiFenShopListWnd", "commerce/jifen_wnd/WithOneJiFenShopList"},	
  	{"CTongNeedFireActivityWnd", "relation/tong/TongNeedFireActivityWnd"},	  
  	{"CMatchGameSignWnd", "activity/fb_action/MatchGameSignWnd"},	
    
    {"CBuyCouponsWnd", "commerce/buy_coupons/BuyCoupons"},	
    {"CCouponsDetailWnd", "commerce/buy_coupons/CouponsDetail"},
    {"CBuyCouponsItemWnd", "commerce/buy_coupons/BuyCouponsItem"},
    {"CBoughtCouponsItemWnd", "commerce/buy_coupons/BoughtCouponsItem"},
    {"CBoughtCouponsDetailWnd", "commerce/buy_coupons/BoughtCouponsDetail"},
	{"CYYCtrl","entrance/login/YYLogin"},
	{"CWeiBo", "open_platform/weibo/WeiBo"},
	{"CNewRoleGuideWnd", "entrance/create_char/NewRoleGuide"},
	{"CNewRoleGuideEndWnd", "entrance/create_char/NewRoleGuideFinish"},
	--系统设置
	{"CSystemSettingParent",	"setting/system_setting/SystemSettingParent"},
	{"CVideoSettingWnd",		"setting/system_setting/VideoSetting"},
	{"CAudioSettingWnd",		"setting/system_setting/AudioSetting"},
	{"CGameSettingWnd",			"setting/system_setting/GameSetting"},
	{"CUISettingWnd",			"setting/system_setting/UISetting"},
	{"SysOtherSettingWnd",		"setting/system_setting/SysOtherSetting"},
	{"CMouseSetting",			"setting/key_map/MouseSetting"},
	
	
	{"CSecretSecurityCardWnd", "entrance/login/SecretSecurityCard"},
}
SetExportClass("gac", ExportTbl)
