function Gac2Gas:PlayActionCyc(Conn, ID, FacialAction, ActionName, Continuance, IsActive, SpecialActionName, ContinuanceSpecial)
--	local Player = Conn.m_Player		
--	if not IsCppBound(Player) then
--		return
--	end
--	local PlayerName = Player.m_Properties:GetCharName()
--	local PlayerID = Player:GetEntityID()
--	if IsActive then
--		if ID and PlayerID == ID then
--			local sMsg = PlayerName.."做了一个"..FacialAction.."的动作!"
--			CChatChannelMgr.SendMsg(sMsg, Player.m_uID, 3)
--			DoAction(Conn, ActionName, Continuance, IsActive, SpecialActionName, ContinuanceSpecial) 	
--		elseif PlayerID ~= ID then
--			local Npc = CCharacterDictator_GetCharacterByID(ID)
--			local Obj = CIntObjServer_GetIntObjServerByID(ID)
--			local Target = Npc or Obj
--			if not Target then
--				return 
--			end
--			local TargetName = Target.m_Properties:GetCharName()
--			local sMsg = Player.m_Properties:GetCharName().."对"..TargetName.."做了一个"..FacialAction.."动作"
--			CChatChannelMgr.SendMsg(sMsg, Player.m_uID, 3)
--			DoActionReaction(Player, FacialActionName, Target)
--		end
--	end
end

--
----播放动作
--function DoAction(Conn, ActionName, Continuance, IsActive, SpecialActionName, ContinuanceSpecial) 
--	local Player = Conn.m_Player
--	if IsActive then
--		if ActionName then
--			Gas2Gac:LoadSpecialEffect(Conn, ActionName, SpecialActionName)
--			IsActive = false
--		end
--	end
--	
--	if Continuance then
--		local function DoFun()
--			Gas2Gac:LoadContinuancelEffect(Conn, Continuance, ContinuanceSpecial)
--		end
--		RegisterOnceTick(Player, "ContinuanceTick", DoFun, 1000, Conn, Continuance, ContinuanceSpecial)
--	end
--end
--
--function DoActionReaction(Player, FacialActionName, Target)
--	local PlayerID = Player:GetEntityID()
--	if FacialActionName then
--		Gas2Gac:LoadSpecialEffect(Conn, ActionName, SpecialActionName)
--	end
--	local sMsg = "大家好哦!"
--	CChatChannelMgr.SendMsg(sMsg, Player.m_uID, 3)
--end

