#pragma once

enum EGas2GacCPPInvoke
{
	eGas2GacCPP_Invoke_Begin = 32768,

	eGas2GacCPP_Fighter_Begin = eGas2GacCPP_Invoke_Begin,
	eGas2GacCPP_OnAgileValueChanged,
	eGas2GacCPP_OnCalValueChanged,
	eGas2GacCPP_OnCtrlValueChanged,
	eGas2GacCPP_OnLevelChanged,
	eGas2GacCPP_OnClassChanged,
	eGas2GacCPP_OnCampChanged,
	eGas2GacCPP_OnPKStateChanged,
	eGas2GacCPP_OnZoneTypeChanged,
	eGas2GacCPP_OnDisplayFightInfo,
	eGas2GacCPP_OnDisplayMagicFightInfo,
	eGas2GacCPP_OnDisplayMsg,
	eGas2GacCPP_OnTalentChanged,
	eGas2GacCPP_OnRemoveTalent,
	eGas2GacCPP_OnCastBegin,
	eGas2GacCPP_OnCastEnd,
	eGas2GacCPP_OnSetNoSingTime,
	eGas2GacCPP_OnSkillBegin,
	eGas2GacCPP_OnMagicCondFail,
	eGas2GacCPP_OnCoolDownBegin,
	eGas2GacCPP_OnCoolDownEnd,
	eGas2GacCPP_OnClearCommonCD,
	eGas2GacCPP_OnAllCoolDownEnd,
	eGas2GacCPP_OnDoMagicOp,
	eGas2GacCPP_OnCastMagicSkill,
	eGas2GacCPP_OnCancelMagicSkill,
	eGas2GacCPP_OnLostTarget,
	eGas2GacCPP_OnBurstSoul,
	eGas2GacCPP_OnArrayCreate,
	eGas2GacCPP_OnArrayValueChange,
	eGas2GacCPP_OnCancelNormalAttack,
	eGas2GacCPP_OnClearState,
	eGas2GacCPP_OnDeleteState,
	eGas2GacCPP_OnSetState,
	eGas2GacCPP_OnSetNormalSkillTarget,
	eGas2GacCPP_OnSyncCastingProcess,
	eGas2GacCPP_OnAddServant,
	eGas2GacCPP_OnGameCampChanged,
	eGas2GacCPP_OnDestroyServant,
	eGas2GacCPP_OnCanBeTakeOver,
	eGas2GacCPP_OnCanNotTakeOver,
	eGas2GacCPP_OnSetAutoNormalAttack,
	eGas2GacCPP_OnDoNormalAttack,
	eGas2GacCPP_OnPrintFightInfo,
	eGas2GacCPP_OnRealNameChange,
	eGas2GacCPP_OnAttackTypeChanged,
	eGas2GacCPP_UpdateSmashRate,
	eGas2GacCPP_OnSyncToSelfCalValueChanged,
	eGas2GacCPP_OnReplaceSkill,
	eGas2GacCPP_OnUseSkillStateChanged,
	eGas2GacCPP_OnRevertSkillCtrlState,
	eGas2GacCPP_OnBurstSoulTimesChanged,
	eGas2GacCPP_Fighter_End,

	eGas2GacCPP_Character_Begin = eGas2GacCPP_Fighter_End,
	eGas2GacCPP_InitFollower,
	eGas2GacCPP_InitFollowerSyncInfo,
	eGas2GacCPP_InitFollowerEnd,
	eGas2GacCPP_OnDead,
	eGas2GacCPP_OnRemoved,
	eGas2GacCPP_OnReborn,
	eGas2GacCPP_OnMoveSpeedChange,
	eGas2GacCPP_DestroyFollower,
	eGas2GacCPP_ClearFollowerSyncInfo,
	eGas2GacCPP_InitDirector,
	eGas2GacCPP_InitDirectorEnd,
	eGas2GacCPP_OnTransfered,
	eGas2GacCPP_BeginTransfer,
	eGas2GacCPP_InitObj,		
	eGas2GacCPP_OnIntoSyncAoi,
	eGas2GacCPP_OnLeaveSyncAoi,
	eGas2GacCPP_OnCancelAutoTrack,
	eGas2GacCPP_DestroyBattleHorse,
	eGas2GacCPP_RemoveTeamMember,
	eGas2GacCPP_TeamSyncInfo,
	eGas2GacCPP_NpcChangeDir,
	eGas2GacCPP_Character_End,
	
	eGas2GacCpp_ApexProxyMsg_Begin,
	eGas2GacCpp_ApexProxyMsg,
	eGas2GacCpp_ApexProxyMsg_End,

	eGas2GacCPP_Invoke_End
};
